name: HowToSWAT
version: '${project.version}'
main: org.howtoswat.HowToSWAT
commands:
  fly:
    description: Schaltet den Flug-Modus um.
    usage: /<command>
  camera:
    description: Versetzt den Spieler in den Zuschauermodus.
    usage: /<command>
  heal:
    description: Heilt den Spieler.
    usage: /<command>
  spawn:
    description: Setzt den Spawnpunkt des Spielers.
    usage: /<command>
  use:
    description: Verwendet eine Droge.
    usage: /<command> [drug]
  equip:
    description: Stattet den Spieler mit Equipment aus.
    usage: /<command> [equip]
  save:
    description: Speichert die aktuelle Equipkonfiguration.
    usage: /<command>
  cooldown:
    description: Setzt sämtliche Cooldowns zurück.
    usage: /<command>
  admins:
    description: Gibt eine Liste an Admins aus/Fügt sie hinzu.
    usage: /<command> ([player])
  builder:
    description: Gibt eine Liste an Buildern aus/Fügt sie hinzu.
    usage: /<command> ([player])
  buildmode:
    description: Betritt/Verlässt den Buildmode.
    usage: /<command>
  baustelle:
    description: Betritt/Verlässt die Baustelle.
    usage: /<command>
  warp:
    description: Tpt den Spieler zu gegebenem Ort.
    usage: /<command> [location]
  navi:
    description: Zeigt eine Route zu gegebenem Ort an.
    usage: /<command> [location]
  luftlinie:
    description: Ändert den Navityp um.
    usage: /<command>
  sprenggürtel:
    description: Zündet einen angezogenen Sprenggürtel.
    usage: /<command> [timer]
  bombe:
    description: Legt pro Spieler eine Bombe.
    usage: /<command>
  annehmen:
    description: Nimmt eine Anfrage an.
    usage: /<command>
  ablehnen:
    description: Lehnt eine Anfrage ab.
    usage: /<command>
  verify:
    description: Verifiziert einen Spieler.
    usage: /<command> [player]
  requestverify:
    description: Stellt eine Verifizierungsanfrage.
    usage: /<command> [player]
  ban:
    description: Bannt einen Spieler.
    usage: /<command> [player] [duration] [reason...]
  kick:
    description: Kickt einen Spieler.
    usage: /<command> [player] [reason...]
  run:
    description: Lässt einen Spieler einen Befehl ausführen.
    usage: /<command> [player] [command...]
  duty:
    description: Betritt den Admin-Modus.
    usage: /<command>
  help:
    description: Gibt eine Liste an Befehlen aus.
    usage: /<command>
  car:
    description: Steuert das Auto eines Spielers.
    usage: /<command> ([find|start])
